---

- hosts: localhost

  pre_tasks:
    - name: Include configuration
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - config.yml
          skip: true
      tags: ['always']

  roles:
    - homebrew
    - mas
    - dock
    - settings
    - rcm
    - iterm2
