---

- hosts: localhost

  pre_tasks:
    - name: Include configuration
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - config.yml
          skip: true
      tags: ['always']

  roles:
    - role: homebrew
      tags: [homebrew]
    - role: mas
      tags: [mas]
    - role: dock
      tags: [dock]
    - role: settings
      tags: [settings]
    - role: rcm
      tags: [rcm]
    # - role: shell
    #   tags: [shell]
