---
- name: Clone dotfiles
  shell: git clone {{ dotfiles.https }} ~/.dotfiles

- name: Switch to ssh remote
  shell: git -C ~/.dotfiles remote set-url origin {{ dotfiles.ssh }}

- name: Run rcup
  shell: rcup
