---
- osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type | 'string' }}"
    value: "{{ item.value }}"
    state: "{{ item.state | 'present' }}"
    with_items: "{{ settings }}"
